In [2]:
import numpy as np


# INTERVIEW QUESTIONS ON NUMPY

In [43]:
#create an array of 10 zeroes
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [44]:
#create an array of 10 ones
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [45]:
#create an array of 10 sevens
7*np.ones(10)

array([7., 7., 7., 7., 7., 7., 7., 7., 7., 7.])

In [46]:
#create an array of integers b/w 10 to 50
np.arange(10 ,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [47]:
#create an array of even integers b/w 10 to 50
np.arange(10 ,51 , 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [48]:
#create a 3 by 3 matrix in range 0 -8
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
#create a 3 by 3 identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
#generate a random no. b/w 0 to 1
np.random.rand()

0.47835076997220094

In [3]:
#generating 10 random integers from (1 to 10)
np.random.randint(1,11,10)

array([7, 4, 2, 3, 8, 8, 3, 1, 2, 4])

In [2]:
#w/o using numpy
import random
randomlist = []
for i in range(0,5):
    n = random.randint(1,30)
    randomlist.append(n)
print(randomlist)

[9, 28, 29, 5, 10]


In [51]:
# to generate array of 25 random numbers from standard normal distribution
np.random.randn(25)

array([-0.75683573, -0.74285262, -0.55789785, -1.09765302,  0.21755106,
        0.8073068 ,  0.0036413 ,  0.91987061,  0.90542136,  0.41452258,
       -0.26108584,  0.74924866,  1.16827262, -1.22055802, -1.03171901,
       -0.09746626, -0.79307957,  0.76080027,  0.72410735, -1.19460683,
       -0.57489453, -1.89441147, -0.83371173, -0.58532736, -0.18941721])

In [52]:
#create an array of 20 elements ranging (0 to 1) which are linearly spaced 
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [54]:
mat=np.arange(1 ,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [55]:
mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [56]:
mat[3,1]

17

In [57]:
mat[0:3 , 1].reshape(3,1)

array([[ 2],
       [ 7],
       [12]])

In [58]:
mat[4:,]

array([[21, 22, 23, 24, 25]])

In [59]:
mat[3:5 ,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [60]:
mat.sum()

325

In [61]:
mat.std()

7.211102550927978

In [62]:
#sum of all columns
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [63]:
#sum of all rows
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [64]:
np.random.rand(100)

array([0.27463745, 0.62356511, 0.79600926, 0.23294435, 0.43471622,
       0.62754961, 0.93340184, 0.32782624, 0.49688617, 0.15802245,
       0.82998186, 0.57719369, 0.8603358 , 0.24424867, 0.83986641,
       0.14050184, 0.47790679, 0.71715827, 0.13443671, 0.38369814,
       0.26106024, 0.91469198, 0.40788537, 0.10307843, 0.54222648,
       0.65572463, 0.70288151, 0.51995309, 0.14847347, 0.19391088,
       0.52500112, 0.90353234, 0.61575813, 0.41138939, 0.78881188,
       0.89087754, 0.425365  , 0.28126154, 0.67454521, 0.49139584,
       0.48870074, 0.14636692, 0.5610928 , 0.84820028, 0.24957712,
       0.94841365, 0.4362923 , 0.68071147, 0.61344478, 0.30212155,
       0.27442373, 0.23243124, 0.2200496 , 0.88938623, 0.58455151,
       0.89286729, 0.77535058, 0.77900587, 0.66219718, 0.04850214,
       0.68804449, 0.50041575, 0.44264985, 0.7863405 , 0.03995043,
       0.75462333, 0.51422921, 0.47800472, 0.64743214, 0.61749555,
       0.8945697 , 0.52589644, 0.26785571, 0.36114503, 0.09451

In [4]:
#numpy 1D array
arr1= np.array([0,0,3,4,4,1,0,3,4,5,1])
arr1

array([0, 0, 3, 4, 4, 1, 0, 3, 4, 5, 1])

In [5]:
#numpy. bincount() method counts the occurrence of each element
np.bincount(arr1)

array([3, 2, 0, 2, 3, 1], dtype=int64)

In [6]:
#NAN VALUE IN NUMPY
arr2= np.array([ 1 , np.nan , 3 , 4 , 5, 6 , np.nan])
arr2

array([ 1., nan,  3.,  4.,  5.,  6., nan])

In [7]:
arr2.sum()

nan

In [8]:
arr2.max()

nan

In [70]:
#HOW TO IGNORE NAN VALUES FROM ARRAY
np.nansum(arr2)

19.0

In [71]:
np.nanmax(arr2)

6.0

In [72]:
#HOW TO REMOVE ELEMENTS FROM ARRAY1 THAT EXIST IN ARRAY2
a= np.array([1,2,4,5,0])
b=np.array([3,4,0])
np.setdiff1d(a,b)

array([1, 2, 5])

In [10]:
#how to calculate percentiles using numpy
c=np.array([11,22,33,44,55,66,77])
perc= np.percentile(c,40)  #RETURN THE 40 PERCENTILE
print(perc)

37.400000000000006


In [74]:
#how to reverse numpy array
rev_arr= c[::-1]
print(rev_arr)

[77 66 55 44 33 22 11]


In [79]:
a=np.arange(4).reshape((2,2))
max_value=np.max(a)
min_value=np.min(a)
print(a)
print(max_value)
print(min_value)

[[0 1]
 [2 3]]
3
0


In [89]:
#calculate mean,median ,std,variamce of array
b=np.arange(16).reshape((4,4))
print(b)
mean=np.mean(b)
med=np.median(b)
std=np.std(b)
variance=np.var(b)
print(mean)
print(med)
print(std)
print(variance)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
7.5
7.5
4.6097722286464435
21.25


In [91]:
#calculate covariance matrix b/w two numpy arrays
a=np.array([2,1,0])
b=np.array([2,3,3])
cov_mat= np.cov(a,b)
print(cov_mat)

[[ 1.         -0.5       ]
 [-0.5         0.33333333]]


In [92]:
#calculate pearson coefficeints relation of 2 ararys
cross_corr= np.corrcoef(a,b)
print(cross_corr)

[[ 1.        -0.8660254]
 [-0.8660254  1.       ]]


In [11]:
#to get the power of each element of array
c=np.arange(5)
print(c)
np.power(c,3)

[0 1 2 3 4]


array([ 0,  1,  8, 27, 64], dtype=int32)

In [12]:
#copy function() & broadcasting
a=np.array([1,2,3,4,5,6,7])
a[3:]=100
print(a)
b=a
print(b)

[  1   2   3 100 100 100 100]
[  1   2   3 100 100 100 100]


In [13]:
#assignment b is assigned a array
b[3:]=500
print(b)
print(a)  #a also get replaced bcoz it is passed as reference variable

[  1   2   3 500 500 500 500]
[  1   2   3 500 500 500 500]


In [106]:
#to avoid this
print(a)
b=a.copy()
b[3:]=1000
print(b)
print(a) #now a has not replaced

[  1   2   3 500 500 500 500]
[   1    2    3 1000 1000 1000 1000]
[  1   2   3 500 500 500 500]


In [111]:
val=4
a<val



array([ True,  True,  True, False, False, False, False])

In [112]:
a[a<val]

array([1, 2, 3])

In [115]:
#selecting random integer in 2D array b/w 0 to 100 of size 8
np.random.randint(0,100,8).reshape(2,4)

array([[25, 60, 43, 81],
       [93, 69, 32, 17]])

In [14]:
np.random.randint(0,101,8)

array([58, 22, 75, 37, 11, 11, 69, 41])